import $ from 'jquery';
import 'bootstrap';
import 'bootstrap/dist/css/bootstrap.min.css';
import './css/styles.css';
import SpaceAge from './js/space-age';

$("#age-input").submit((event) => {
  event.preventDefault();
  let userAge = $("#your-age").val();
  let yourAge = new SpaceAge(userAge);
  yourAge.ageConverter();
  $("#output").fadeIn();
  $("#mercury-age").text(yourAge.ages['Mercury']);
  $("#mercury-lifespan").text(yourAge.expectancy['Mercury']);
  $("#mercury-foretelling").text(yourAge.foretelling('Mercury'));
  $("#venus-age").text(yourAge.ages['Venus']);
  $("#venus-lifespan").text(yourAge.expectancy['Venus']);
  $("#venus-foretelling").text(yourAge.foretelling('Venus'));
  $("#earth-age").text(yourAge.ages['Earth']);
  $("#earth-lifespan").text(yourAge.expectancy['Earth']);
  $("#earth-foretelling").text(yourAge.foretelling('Earth'));
  $("#mars-age").text(yourAge.ages['Mars']);
  $("#mars-lifespan").text(yourAge.expectancy['Mars']);
  $("#mars-foretelling").text(yourAge.foretelling('Mars'));
  $("#jupiter-age").text(yourAge.ages['Jupiter']);
  $("#jupiter-lifespan").text(yourAge.expectancy['Jupiter']);
  $("#jupiter-foretelling").text(yourAge.foretelling('Jupiter'));
  $("#saturn-age").text(yourAge.ages['Saturn']);
  $("#saturn-lifespan").text(yourAge.expectancy['Saturn']);
  $("#saturn-foretelling").text(yourAge.foretelling('Saturn'));
  $("#uranus-age").text(yourAge.ages['Uranus']);
  $("#uranus-lifespan").text(yourAge.expectancy['Uranus']);
  $("#uranus-foretelling").text(yourAge.foretelling('Uranus'));
  $("#neptune-age").text(yourAge.ages['Neptune']);
  $("#neptune-lifespan").text(yourAge.expectancy['Neptune']);
  $("#neptune-foretelling").text(yourAge.foretelling('Neptune'));
  $("#pluto-age").text(yourAge.ages['Pluto']);
  $("#pluto-lifespan").text(yourAge.expectancy['Pluto']);
  $("#pluto-foretelling").text(yourAge.foretelling('Pluto'));

});